apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: sock-shop
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      app: payment-service # 针对支付服务
  delay:
    latency: "500ms" # 500ms延迟
  duration: "2m" # 持续2分钟