apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: payment-delay2
  namespace: online-boutique1
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      "app": "payment"
  delay:
    latency: "500ms"    # 延迟500毫秒
  duration: "5m"        # 持续5分钟 